{% set version = "0.1.0" %}

package:
  name: pywfm
  version: {{ version }}

source:
  git_url: https://github.com/SGMOModeling/PyWFM.git
  git_tag: embed-dll

build:
  noarch: python
  number: 0
  script: python -m pip install --ignore-installed .

requirements:
  host:
    - python>=3.6
    - pip
    - git
    - pandas
    - numpy
    - matplotlib
    - iwfmdll
  
  run:
    - python>=3.6
    - git
    - pandas
    - numpy
    - matplotlib
    - iwfmdll

test:
  imports:
    - pywfm

about:
  home: https://github.com/SGMOModeling/PyWFM
  license: MIT
  summary: 'python library to interact with IWFM applications'
  description: |
    python library to expose the functionality of the IWFM DLL
  dev_url:  https://github.com/SGMOModeling/PyWFM
  doc_url: https://sgmomodeling.github.io/PyWFM/html/index.html
